import { Meal } from '../app/types'; // Adjust path to your types file if needed

export const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];

export const mealTypes = { 
    breakfast: { icon: "cafe-outline" as const }, 
    lunch: { icon: "restaurant-outline" as const }, 
    dinner: { icon: "moon-outline" as const }, 
    snack: { icon: "pizza-outline" as const }, 
};

// --- MEAL COMPONENT DATABASES ---

export const BREAKFAST_DB: Meal[] = [
    { id: "B001", name: "Scrambled Eggs with Toast", image: "https://images.unsplash.com/photo-1525351484163-7529414344d8", ingredients: [ { name: "Eggs", baseQuantity: 2, unit: "large", perPerson: true }, { name: "Milk", baseQuantity: 1, unit: "tbsp", perPerson: true }, { name: "Butter", baseQuantity: 0.5, unit: "tbsp", perPerson: true }, { name: "Bread", baseQuantity: 2, unit: "slices", perPerson: true } ], nutrition: { calories: 350, protein: 20, carbs: 25, fat: 18 }, recipe: "Whisk {{Eggs}} with {{Milk}}, salt, and pepper. Melt {{Butter}} in a non-stick skillet over medium heat. Pour in the egg mixture and cook, stirring gently, until softly set. Serve immediately with {{Bread}} of toast.", tags: ['vegetarian', 'nut-free', 'contains:dairy', 'contains:gluten', 'contains:eggs'], type: 'breakfast' },
    { id: "B002", name: "Avocado Toast with Chili Flakes", image: "https://images.unsplash.com/photo-1584308666744-8480436313ae", ingredients: [ { name: "Sourdough Bread", baseQuantity: 1, unit: "slice", perPerson: true }, { name: "Avocado", baseQuantity: 0.5, unit: "whole", perPerson: true }, { name: "Chili Flakes", baseQuantity: 1, unit: "pinch", perPerson: false } ], nutrition: { calories: 300, protein: 10, carbs: 35, fat: 15 }, recipe: "Toast {{Sourdough Bread}} until golden brown. Mash the {{Avocado}} and spread it evenly on the toast. Sprinkle with {{Chili Flakes}} and a pinch of salt.", tags: ['vegan', 'vegetarian', 'dairy-free', 'nut-free', 'contains:gluten'], type: 'breakfast' },
    { id: "B003", name: "Greek Yogurt with Berries & Honey", image: "https://images.unsplash.com/photo-1559847844-5315695d0e66", ingredients: [ { name: "Greek Yogurt", baseQuantity: 1, unit: "cup", perPerson: true }, { name: "Mixed Berries", baseQuantity: 0.5, unit: "cup", perPerson: true }, { name: "Honey", baseQuantity: 1, unit: "tsp", perPerson: true } ], nutrition: { calories: 250, protein: 18, carbs: 20, fat: 10 }, recipe: "Spoon {{Greek Yogurt}} into a bowl. Top with {{Mixed Berries}} and drizzle with {{Honey}}.", tags: ['vegetarian', 'gluten-free', 'nut-free', 'contains:dairy'], type: 'breakfast' },
    { id: "B004", name: "Tofu Scramble with Spinach", image: "https://images.unsplash.com/photo-1595854341625-f33ee10dbf94", ingredients: [ { name: "Firm Tofu", baseQuantity: 150, unit: "g", perPerson: true }, { name: "Spinach", baseQuantity: 1, unit: "cup", perPerson: true }, { name: "Turmeric", baseQuantity: 0.25, unit: "tsp", perPerson: false } ], nutrition: { calories: 280, protein: 25, carbs: 5, fat: 18 }, recipe: "Crumble {{Firm Tofu}} into a warm pan. Sprinkle with {{Turmeric}} for color and cook for 5 minutes. Wilt in {{Spinach}} and season with salt and pepper.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'breakfast' },
    { id: "B005", name: "Protein Smoothie", image: "https://images.unsplash.com/photo-1610970881699-44a5c8a0f1b2", ingredients: [ { name: "Protein Powder", baseQuantity: 1, unit: "scoop", perPerson: true }, { name: "Banana", baseQuantity: 1, unit: "whole", perPerson: true }, { name: "Plant Milk", baseQuantity: 250, unit: "ml", perPerson: true } ], nutrition: { calories: 350, protein: 30, carbs: 40, fat: 8 }, recipe: "Blend {{Protein Powder}}, {{Banana}}, and {{Plant Milk}} until smooth.", tags: ['vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'vegan-optional'], type: 'breakfast' },
    { id: "B006", name: "Oatmeal with Almonds & Banana", image: "https://images.unsplash.com/photo-1596704122365-bf045a1c1a25", ingredients: [ { name: "Rolled Oats", baseQuantity: 50, unit: "g", perPerson: true }, { name: "Almonds", baseQuantity: 10, unit: "g", perPerson: true }, { name: "Banana", baseQuantity: 0.5, unit: "whole", perPerson: true } ], nutrition: { calories: 380, protein: 12, carbs: 60, fat: 10 }, recipe: "Cook {{Rolled Oats}} until creamy. Top with sliced {{Banana}} and {{Almonds}}.", tags: ['vegan', 'vegetarian', 'dairy-free', 'gluten-free-optional', 'contains:nuts'], type: 'breakfast' },
    { id: "B007", name: "Smoked Salmon Bagel", image: "https://images.unsplash.com/photo-1591289133633-a17289528148", ingredients: [ { name: "Bagel", baseQuantity: 1, unit: "whole", perPerson: true }, { name: "Cream Cheese", baseQuantity: 2, unit: "tbsp", perPerson: true }, { name: "Smoked Salmon", baseQuantity: 50, unit: "g", perPerson: true } ], nutrition: { calories: 450, protein: 25, carbs: 50, fat: 18 }, recipe: "Toast {{Bagel}}, spread with {{Cream Cheese}} and top with {{Smoked Salmon}}.", tags: ['nut-free', 'contains:gluten', 'contains:dairy'], type: 'breakfast'},
    { id: "B008", name: "Breakfast Burrito", image: "https://images.unsplash.com/photo-1565565576132-23b246a4a602", ingredients: [ { name: "Tortilla", baseQuantity: 1, unit: "large", perPerson: true }, { name: "Scrambled Eggs", baseQuantity: 2, unit: "eggs worth", perPerson: true }, { name: "Sausage", baseQuantity: 50, unit: "g", perPerson: true }, { name: "Cheese", baseQuantity: 0.25, unit: "cup", perPerson: true } ], nutrition: { calories: 550, protein: 30, carbs: 40, fat: 30 }, recipe: "Fill a warm {{Tortilla}} with {{Scrambled Eggs}}, cooked {{Sausage}}, and {{Cheese}}.", tags: ['nut-free', 'contains:gluten', 'contains:dairy', 'contains:eggs'], type: 'breakfast'},
    { id: "B009", name: "Chia Seed Pudding", image: "https://images.unsplash.com/photo-1505252585461-14570007cd18", ingredients: [ { name: "Chia Seeds", baseQuantity: 3, unit: "tbsp", perPerson: true }, { name: "Plant Milk", baseQuantity: 1, unit: "cup", perPerson: true }, { name: "Maple Syrup", baseQuantity: 1, unit: "tbsp", perPerson: true } ], nutrition: { calories: 300, protein: 10, carbs: 35, fat: 15 }, recipe: "Mix {{Chia Seeds}}, {{Plant Milk}}, and {{Maple Syrup}}. Refrigerate for at least 2 hours or overnight. Serve chilled.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'breakfast'},
    { id: "B010", name: "Cottage Cheese with Pineapple", image: "https://images.unsplash.com/photo-1628920799849-99434188681e", ingredients: [ { name: "Cottage Cheese", baseQuantity: 1, unit: "cup", perPerson: true }, { name: "Pineapple Chunks", baseQuantity: 0.5, unit: "cup", perPerson: true } ], nutrition: { calories: 180, protein: 20, carbs: 18, fat: 3 }, recipe: "Spoon {{Cottage Cheese}} into a bowl and top with {{Pineapple Chunks}}.", tags: ['vegetarian', 'gluten-free', 'nut-free', 'contains:dairy'], type: 'breakfast'},
    { id: "B011", name: "French Toast", image: "https://images.unsplash.com/photo-1587311409943-7853507204f3", ingredients: [ { name: "Bread", baseQuantity: 2, unit: "slices", perPerson: true }, { name: "Egg", baseQuantity: 1, unit: "large", perPerson: true }, { name: "Milk", baseQuantity: 0.25, unit: "cup", perPerson: true } ], nutrition: { calories: 400, protein: 15, carbs: 50, fat: 15 }, recipe: "Whisk {{Egg}} and {{Milk}}. Dip {{Bread}} into the mixture and cook on a buttered skillet until golden brown on both sides.", tags: ['vegetarian', 'nut-free', 'contains:gluten', 'contains:dairy', 'contains:eggs'], type: 'breakfast'},
    { id: "B012", name: "Breakfast Quiche Slice", image: "https://images.unsplash.com/photo-1588625511396-85c49b6b9319", ingredients: [ { name: "Pie Crust", baseQuantity: 0.125, unit: "slice", perPerson: true }, { name: "Eggs", baseQuantity: 2, unit: "large", perPerson: true }, { name: "Spinach", baseQuantity: 0.5, unit: "cup", perPerson: true } ], nutrition: { calories: 320, protein: 18, carbs: 15, fat: 20 }, recipe: "A savory and filling breakfast bake.", tags: ['vegetarian', 'nut-free', 'contains:gluten', 'contains:dairy', 'contains:eggs'], type: 'breakfast'},
    { id: "B013", name: "Shakshuka", image: "https://images.unsplash.com/photo-1590412200988-a436970781fa", ingredients: [{ name: "Eggs", baseQuantity: 2, unit: "large", perPerson: true }, { name: "Tomato Sauce", baseQuantity: 1, unit: "cup", perPerson: true }, { name: "Feta Cheese", baseQuantity: 0.25, unit: "cup", perPerson: true }], nutrition: { calories: 400, protein: 22, carbs: 20, fat: 25 }, recipe: "Simmer {{Tomato Sauce}} in a skillet, make wells and crack in {{Eggs}}. Cook until whites are set. Top with {{Feta Cheese}}.", tags: ['vegetarian', 'gluten-free', 'nut-free', 'contains:dairy', 'contains:eggs'], type: 'breakfast' },
    { id: "B014", name: "Protein Pancakes", image: "https://images.unsplash.com/photo-1554102319-CF5643443d39", ingredients: [{ name: "Protein Powder", baseQuantity: 1, unit: "scoop", perPerson: true }, { name: "Banana", baseQuantity: 1, unit: "whole", perPerson: true }, { name: "Egg", baseQuantity: 1, unit: "large", perPerson: true }], nutrition: { calories: 380, protein: 30, carbs: 45, fat: 8 }, recipe: "Mash {{Banana}} and mix with {{Protein Powder}} and {{Egg}}. Cook on a lightly oiled griddle.", tags: ['vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'contains:eggs'], type: 'breakfast' },
    { id: "B015", name: "Acai Smoothie Bowl", image: "https://images.unsplash.com/photo-1534353436294-0dbd4bdac845", ingredients: [{ name: "Frozen Acai Puree", baseQuantity: 100, unit: "g", perPerson: true }, { name: "Banana", baseQuantity: 0.5, unit: "whole", perPerson: true }, { name: "Granola", baseQuantity: 0.25, unit: "cup", perPerson: true }], nutrition: { calories: 350, protein: 5, carbs: 60, fat: 12 }, recipe: "Blend {{Frozen Acai Puree}} with {{Banana}} until thick and smooth. Pour into a bowl and top with {{Granola}}.", tags: ['vegan', 'vegetarian', 'dairy-free', 'contains:nuts-optional', 'contains:gluten-optional'], type: 'breakfast' },
    { id: "B016", name: "Belgian Waffles with Fruit", image: "https://images.unsplash.com/photo-1562376552-0d160a2f86d6", ingredients: [{ name: "Waffle Batter", baseQuantity: 1, unit: "cup", perPerson: true }, { name: "Strawberries", baseQuantity: 0.5, unit: "cup", perPerson: true }], nutrition: { calories: 450, protein: 10, carbs: 70, fat: 15 }, recipe: "Cook {{Waffle Batter}} in a waffle iron until golden. Top with sliced {{Strawberries}}.", tags: ['vegetarian', 'nut-free', 'contains:gluten', 'contains:dairy', 'contains:eggs'], type: 'breakfast' },
    { id: "B017", name: "English Muffin with Egg & Cheese", image: "https://images.unsplash.com/photo-1629813254924-a764d4d6852c", ingredients: [{ name: "English Muffin", baseQuantity: 1, unit: "whole", perPerson: true }, { name: "Fried Egg", baseQuantity: 1, unit: "large", perPerson: true }, { name: "Cheese Slice", baseQuantity: 1, unit: "slice", perPerson: true }], nutrition: { calories: 350, protein: 18, carbs: 30, fat: 18 }, recipe: "Toast the {{English Muffin}}. Top with a {{Fried Egg}} and a {{Cheese Slice}}.", tags: ['vegetarian', 'nut-free', 'contains:gluten', 'contains:dairy', 'contains:eggs'], type: 'breakfast' },
    { id: "B018", name: "Breakfast Tacos", image: "https://images.unsplash.com/photo-1632773983815-a1d632599645", ingredients: [{ name: "Corn Tortillas", baseQuantity: 2, unit: "small", perPerson: true }, { name: "Scrambled Eggs", baseQuantity: 2, unit: "eggs worth", perPerson: true }, { name: "Salsa", baseQuantity: 2, unit: "tbsp", perPerson: true }], nutrition: { calories: 320, protein: 15, carbs: 25, fat: 16 }, recipe: "Warm {{Corn Tortillas}}. Fill with {{Scrambled Eggs}} and top with {{Salsa}}.", tags: ['vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'contains:eggs'], type: 'breakfast' },
    { id: "B019", name: "Croissant with Jam", image: "https://images.unsplash.com/photo-1587241321921-542a3838744b", ingredients: [{ name: "Croissant", baseQuantity: 1, unit: "large", perPerson: true }, { name: "Jam", baseQuantity: 1, unit: "tbsp", perPerson: true }], nutrition: { calories: 350, protein: 5, carbs: 45, fat: 18 }, recipe: "Slice a {{Croissant}} and spread with your favorite {{Jam}}.", tags: ['vegetarian', 'nut-free', 'contains:gluten', 'contains:dairy'], type: 'breakfast' },
    { id: "B020", name: "Vegan Breakfast Sausage Patties", image: "https://images.unsplash.com/photo-1621932763548-8c5603813f80", ingredients: [{ name: "Vegan Sausage", baseQuantity: 2, unit: "patties", perPerson: true }], nutrition: { calories: 200, protein: 18, carbs: 8, fat: 12 }, recipe: "Cook {{Vegan Sausage}} in a skillet until browned on both sides.", tags: ['vegan', 'vegetarian', 'dairy-free', 'nut-free', 'contains:gluten-optional'], type: 'breakfast' },
    { id: "B021", name: "Cinnamon Roll", image: "https://images.unsplash.com/photo-1621204024198-33d3c0356193", ingredients: [{ name: "Cinnamon Roll", baseQuantity: 1, unit: "large", perPerson: true }], nutrition: { calories: 420, protein: 6, carbs: 65, fat: 16 }, recipe: "A warm, gooey cinnamon roll.", tags: ['vegetarian', 'nut-free', 'contains:gluten', 'contains:dairy', 'contains:eggs'], type: 'breakfast' },
    { id: "B022", name: "Fruit Salad with Mint", image: "https://images.unsplash.com/photo-1559181567-c3190ca9959b", ingredients: [{ name: "Mixed Fruit", baseQuantity: 2, unit: "cups", perPerson: true }, { name: "Mint Leaves", baseQuantity: 2, unit: "sprigs", perPerson: true }], nutrition: { calories: 150, protein: 2, carbs: 35, fat: 1 }, recipe: "Chop a variety of {{Mixed Fruit}} like melon, berries, and kiwi. Garnish with fresh {{Mint Leaves}}.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'breakfast' },
    { id: "B023", name: "Granola with Plant Milk", image: "https://images.unsplash.com/photo-1464195979928-04a433438da6", ingredients: [{ name: "Granola", baseQuantity: 0.75, unit: "cup", perPerson: true }, { name: "Plant Milk", baseQuantity: 1, unit: "cup", perPerson: true }], nutrition: { calories: 450, protein: 12, carbs: 60, fat: 20 }, recipe: "Pour {{Plant Milk}} over a bowl of crunchy {{Granola}}.", tags: ['vegan', 'vegetarian', 'dairy-free', 'contains:nuts', 'contains:gluten'], type: 'breakfast' },
    { id: "B024", name: "Kippers on Toast", image: "https://images.unsplash.com/photo-1519693431681-192b95b46b60", ingredients: [{ name: "Kipper Fillets", baseQuantity: 100, unit: "g", perPerson: true }, { name: "Toast", baseQuantity: 1, unit: "slice", perPerson: true }], nutrition: { calories: 320, protein: 25, carbs: 15, fat: 18 }, recipe: "Grill or poach {{Kipper Fillets}} and serve on top of buttered {{Toast}}.", tags: ['nut-free', 'dairy-free-optional', 'contains:gluten'], type: 'breakfast' },
    { id: "B025", name: "Congee (Rice Porridge)", image: "https://images.unsplash.com/photo-1628342419818-a6e4d2a13c24", ingredients: [{ name: "Cooked Rice", baseQuantity: 1, unit: "cup", perPerson: true }, { name: "Chicken Broth", baseQuantity: 2, unit: "cups", perPerson: true }], nutrition: { calories: 250, protein: 10, carbs: 50, fat: 2 }, recipe: "Simmer {{Cooked Rice}} in {{Chicken Broth}} until it breaks down into a thick porridge. Garnish as desired.", tags: ['gluten-free', 'dairy-free', 'nut-free'], type: 'breakfast' },
    { id: "B026", name: "Dutch Baby Pancake", image: "https://images.unsplash.com/photo-1558032762-28a883b27218", ingredients: [{ name: "Flour", baseQuantity: 0.5, unit: "cup", perPerson: true }, { name: "Egg", baseQuantity: 2, unit: "large", perPerson: true }, { name: "Milk", baseQuantity: 0.5, unit: "cup", perPerson: true }], nutrition: { calories: 400, protein: 15, carbs: 40, fat: 20 }, recipe: "Blend {{Flour}}, {{Egg}}, and {{Milk}}. Pour into a hot, buttered skillet and bake at 220°C/425°F until puffed and golden.", tags: ['vegetarian', 'nut-free', 'contains:gluten', 'contains:dairy', 'contains:eggs'], type: 'breakfast' },
    { id: "B027", name: "Cream of Wheat", image: "https://images.unsplash.com/photo-1588919685413-5a63a56b46b8", ingredients: [{ name: "Cream of Wheat", baseQuantity: 0.5, unit: "cup", perPerson: true }, { name: "Water", baseQuantity: 1, unit: "cup", perPerson: true }], nutrition: { calories: 200, protein: 6, carbs: 42, fat: 1 }, recipe: "Prepare {{Cream of Wheat}} with {{Water}} according to package directions. Serve with milk and sugar.", tags: ['vegetarian', 'nut-free', 'dairy-free-optional', 'contains:gluten'], type: 'breakfast' },
    { id: "B028", name: "Poached Eggs on Spinach", image: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543", ingredients: [{ name: "Eggs", baseQuantity: 2, unit: "large", perPerson: true }, { name: "Spinach", baseQuantity: 2, unit: "cups", perPerson: true }], nutrition: { calories: 180, protein: 14, carbs: 4, fat: 12 }, recipe: "Wilt {{Spinach}} in a pan. Poach {{Eggs}} and serve on top of the spinach.", tags: ['vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'contains:eggs'], type: 'breakfast' },
    { id: "B029", name: "Crêpes with Lemon & Sugar", image: "https://images.unsplash.com/photo-1587329249718-3a434c764e51", ingredients: [{ name: "Crêpe", baseQuantity: 2, unit: "large", perPerson: true }, { name: "Lemon Juice", baseQuantity: 1, unit: "tbsp", perPerson: true }, { name: "Sugar", baseQuantity: 1, unit: "tbsp", perPerson: true }], nutrition: { calories: 300, protein: 8, carbs: 50, fat: 8 }, recipe: "Cook thin {{Crêpe}}. Squeeze with {{Lemon Juice}} and sprinkle with {{Sugar}}. Roll up and serve.", tags: ['vegetarian', 'nut-free', 'contains:gluten', 'contains:dairy', 'contains:eggs'], type: 'breakfast' },
    { id: "B030", name: "Muesli with Sliced Peaches", image: "https://images.unsplash.com/photo-1565599244243-be1947192350", ingredients: [{ name: "Muesli", baseQuantity: 1, unit: "cup", perPerson: true }, { name: "Peach", baseQuantity: 1, unit: "whole", perPerson: true }], nutrition: { calories: 380, protein: 10, carbs: 75, fat: 6 }, recipe: "Pour muesli into a bowl and top with fresh sliced peaches. Add milk if desired.", tags: ['vegetarian', 'dairy-free-optional', 'contains:nuts', 'contains:gluten'], type: 'breakfast' },
];

export const SNACK_DB: Meal[] = [
    { id: "S001", name: "Apple with Peanut Butter", image: "https://images.unsplash.com/photo-1568584708969-0414161a3b98", ingredients: [ { name: "Apple", baseQuantity: 1, unit: "whole", perPerson: true }, { name: "Peanut Butter", baseQuantity: 2, unit: "tbsp", perPerson: true } ], nutrition: { calories: 280, protein: 8, carbs: 30, fat: 16 }, recipe: "Slice the {{Apple}} and serve with {{Peanut Butter}} for dipping.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'contains:peanuts'], type: 'snack' },
    { id: "S002", name: "Handful of Almonds", image: "https://images.unsplash.com/photo-1508061233810-big5955009e0", ingredients: [ { name: "Almonds", baseQuantity: 0.25, unit: "cup", perPerson: true } ], nutrition: { calories: 170, protein: 6, carbs: 6, fat: 14 }, recipe: "A simple, healthy snack.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'contains:nuts'], type: 'snack' },
    { id: "S003", name: "Hard Boiled Egg", image: "https://images.unsplash.com/photo-1590502593493-5773a2b73373", ingredients: [ { name: "Egg", baseQuantity: 1, unit: "large", perPerson: true } ], nutrition: { calories: 78, protein: 6, carbs: 1, fat: 5 }, recipe: "A single hard boiled egg.", tags: ['vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'contains:eggs'], type: 'snack' },
    { id: "S004", name: "Greek Yogurt Pot", image: "https://images.unsplash.com/photo-1605697298328-932c1c6e1a49", ingredients: [ { name: "Greek Yogurt", baseQuantity: 0.75, unit: "cup", perPerson: true } ], nutrition: { calories: 150, protein: 15, carbs: 10, fat: 5 }, recipe: "Creamy and satisfying.", tags: ['vegetarian', 'gluten-free', 'nut-free', 'contains:dairy'], type: 'snack' },
    { id: "S005", name: "Rice Cakes with Hummus", image: "https://images.unsplash.com/photo-1627885239920-77a296157a91", ingredients: [ { name: "Rice Cakes", baseQuantity: 2, unit: "cakes", perPerson: true }, { name: "Hummus", baseQuantity: 2, unit: "tbsp", perPerson: true } ], nutrition: { calories: 200, protein: 7, carbs: 35, fat: 5 }, recipe: "Spread {{Hummus}} on {{Rice Cakes}}.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'snack' },
    { id: "S006", name: "Beef Jerky", image: "https://images.unsplash.com/photo-1582236396915-d67295d85574", ingredients: [ { name: "Beef Jerky", baseQuantity: 30, unit: "g", perPerson: true } ], nutrition: { calories: 120, protein: 15, carbs: 5, fat: 5 }, recipe: "A savory, protein-packed snack.", tags: ['gluten-free-optional', 'dairy-free', 'nut-free'], type: 'snack' },
    { id: "S007", name: "Protein Bar", image: "https://images.unsplash.com/photo-1625769749729-216a4e3b1464", ingredients: [ { name: "Protein Bar", baseQuantity: 1, unit: "bar", perPerson: true } ], nutrition: { calories: 220, protein: 20, carbs: 25, fat: 8 }, recipe: "Great for post-workout fuel.", tags: ['vegetarian', 'gluten-free-optional', 'dairy-free-optional', 'contains:nuts-optional', 'contains:peanuts-optional'], type: 'snack' },
    { id: "S008", name: "Carrot Sticks with Hummus", image: "https://images.unsplash.com/photo-1598170845033-5c3f3366a172", ingredients: [ { name: "Baby Carrots", baseQuantity: 1, unit: "cup", perPerson: true }, { name: "Hummus", baseQuantity: 3, unit: "tbsp", perPerson: true } ], nutrition: { calories: 150, protein: 5, carbs: 20, fat: 6 }, recipe: "A fresh and healthy choice.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'snack' },
    { id: "S009", name: "Small bowl of Olives", image: "https://images.unsplash.com/photo-1572527788148-933df42167d6", ingredients: [ { name: "Olives", baseQuantity: 0.5, unit: "cup", perPerson: true } ], nutrition: { calories: 100, protein: 1, carbs: 5, fat: 10 }, recipe: "A savory, low-carb snack.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'snack' },
    { id: "S010", name: "Popcorn", image: "https://images.unsplash.com/photo-1578849223126-a8ed29412f86", ingredients: [ { name: "Popped Popcorn", baseQuantity: 3, unit: "cups", perPerson: true } ], nutrition: { calories: 150, protein: 4, carbs: 30, fat: 2 }, recipe: "A light and high-fiber snack.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'snack' },
    { id: "S011", name: "Dark Chocolate Square", image: "https://images.unsplash.com/photo-1541492922184-486a3d6d03b3", ingredients: [ { name: "Dark Chocolate", baseQuantity: 25, unit: "g", perPerson: true } ], nutrition: { calories: 150, protein: 2, carbs: 10, fat: 12 }, recipe: "A satisfying sweet treat.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'snack' },
    { id: "S012", name: "Trail Mix", image: "https://images.unsplash.com/photo-1600891964344-23a6b57904a6", ingredients: [ { name: "Trail Mix", baseQuantity: 0.25, unit: "cup", perPerson: true } ], nutrition: { calories: 250, protein: 8, carbs: 20, fat: 16 }, recipe: "A mix of nuts, seeds, and dried fruit for energy.", tags: ['vegetarian', 'gluten-free', 'dairy-free', 'contains:nuts', 'contains:peanuts'], type: 'snack' },
    { id: "S013", name: "Edamame", image: "https://images.unsplash.com/photo-1551024351-6559134b2f1c", ingredients: [{ name: "Edamame in pods", baseQuantity: 1, unit: "cup", perPerson: true }], nutrition: { calories: 190, protein: 17, carbs: 15, fat: 8 }, recipe: "Steam {{Edamame in pods}} and sprinkle with sea salt.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'snack' },
    { id: "S014", name: "Cottage Cheese with Peach", image: "https://images.unsplash.com/photo-1584279222348-114444589d31", ingredients: [{ name: "Cottage Cheese", baseQuantity: 0.5, unit: "cup" }, { name: "Peach", baseQuantity: 1, unit: "whole" }], nutrition: { calories: 150, protein: 15, carbs: 15, fat: 3 }, recipe: "Top {{Cottage Cheese}} with sliced {{Peach}}.", tags: ['vegetarian', 'gluten-free', 'nut-free', 'contains:dairy'], type: 'snack' },
    { id: "S015", name: "Celery with Cream Cheese", image: "https://images.unsplash.com/photo-1624523019085-36035787034b", ingredients: [{ name: "Celery Sticks", baseQuantity: 2, unit: "stalks" }, { name: "Cream Cheese", baseQuantity: 2, unit: "tbsp" }], nutrition: { calories: 120, protein: 2, carbs: 4, fat: 10 }, recipe: "Spread {{Cream Cheese}} on {{Celery Sticks}}.", tags: ['vegetarian', 'gluten-free', 'nut-free', 'contains:dairy'], type: 'snack' },
    { id: "S016", name: "Seaweed Snacks", image: "https://images.unsplash.com/photo-1583316175778-220133883a2b", ingredients: [{ name: "Roasted Seaweed", baseQuantity: 1, unit: "pack" }], nutrition: { calories: 30, protein: 2, carbs: 1, fat: 2 }, recipe: "Crispy, savory roasted seaweed sheets.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'snack' },
    { id: "S017", name: "A handful of Walnuts", image: "https://images.unsplash.com/photo-1596622718113-a42c41a4a2a1", ingredients: [{ name: "Walnuts", baseQuantity: 0.25, unit: "cup" }], nutrition: { calories: 190, protein: 4, carbs: 4, fat: 18 }, recipe: "A simple snack rich in omega-3s.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'contains:nuts'], type: 'snack' },
    { id: "S018", name: "Grapes", image: "https://images.unsplash.com/photo-1597393224744-3d3527a0572d", ingredients: [{ name: "Grapes", baseQuantity: 1, unit: "cup" }], nutrition: { calories: 104, protein: 1, carbs: 27, fat: 0 }, recipe: "A sweet and hydrating fruit snack.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'snack' },
    { id: "S019", name: "Turkey Slices", image: "https://images.unsplash.com/photo-1626081494238-b4885a11476b", ingredients: [{ name: "Sliced Turkey Breast", baseQuantity: 100, unit: "g" }], nutrition: { calories: 110, protein: 22, carbs: 1, fat: 2 }, recipe: "A few slices of lean turkey breast.", tags: ['gluten-free', 'dairy-free', 'nut-free'], type: 'snack' },
    { id: "S020", name: "Cheese Cubes", image: "https://images.unsplash.com/photo-1608666564212-58410879059a", ingredients: [{ name: "Cheddar Cheese", baseQuantity: 40, unit: "g" }], nutrition: { calories: 160, protein: 10, carbs: 1, fat: 13 }, recipe: "Cubes of your favorite cheese.", tags: ['vegetarian', 'gluten-free', 'nut-free', 'contains:dairy'], type: 'snack' },
    { id: "S021", name: "Pickles", image: "https://images.unsplash.com/photo-1581331393596-a07e33178044", ingredients: [{ name: "Dill Pickles", baseQuantity: 2, unit: "spears" }], nutrition: { calories: 10, protein: 0, carbs: 2, fat: 0 }, recipe: "A crunchy, low-calorie, savory snack.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'snack' },
    { id: "S022", name: "Avocado Half", image: "https://images.unsplash.com/photo-1587341689313-2f6d45f36554", ingredients: [{ name: "Avocado", baseQuantity: 0.5, unit: "whole" }], nutrition: { calories: 160, protein: 2, carbs: 9, fat: 15 }, recipe: "Half an avocado sprinkled with salt and pepper.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'snack' },
    { id: "S023", name: "Bell Pepper Slices", image: "https://images.unsplash.com/photo-1599547443189-5ab8a3c3f964", ingredients: [{ name: "Bell Pepper", baseQuantity: 1, unit: "whole" }], nutrition: { calories: 30, protein: 1, carbs: 7, fat: 0 }, recipe: "Crunchy and refreshing slices of bell pepper.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'snack' },
    { id: "S024", name: "Sun-dried Tomatoes", image: "https://images.unsplash.com/photo-1590779431526-575988390977", ingredients: [{ name: "Sun-dried Tomatoes", baseQuantity: 0.5, unit: "cup" }], nutrition: { calories: 140, protein: 8, carbs: 23, fat: 3 }, recipe: "Chewy, sweet, and savory tomatoes.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'snack' },
    { id: "S025", name: "A small Banana", image: "https://images.unsplash.com/photo-1587132137056-bfbf0166836e", ingredients: [{ name: "Banana", baseQuantity: 1, unit: "small" }], nutrition: { calories: 90, protein: 1, carbs: 23, fat: 0 }, recipe: "A classic, potassium-rich fruit.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'snack' },
    { id: "S026", name: "Cucumber Slices", image: "https://images.unsplash.com/photo-1591192375303-532d183c564d", ingredients: [{ name: "Cucumber", baseQuantity: 1, unit: "cup sliced" }], nutrition: { calories: 16, protein: 1, carbs: 4, fat: 0 }, recipe: "Cool, crunchy, and hydrating.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'snack' },
    { id: "S027", name: "Roasted Chickpeas", image: "https://images.unsplash.com/photo-1630409349883-4852d262a13f", ingredients: [{ name: "Chickpeas", baseQuantity: 0.5, unit: "cup" }], nutrition: { calories: 140, protein: 7, carbs: 22, fat: 4 }, recipe: "Toss {{Chickpeas}} with olive oil and spices, then roast until crispy.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'snack' },
    { id: "S028", name: "Pistachios", image: "https://images.unsplash.com/photo-1596778401399-22a4c52a0a2a", ingredients: [{ name: "Pistachios", baseQuantity: 0.25, unit: "cup" }], nutrition: { calories: 160, protein: 6, carbs: 8, fat: 13 }, recipe: "A handful of delicious pistachios.", tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'contains:nuts'], type: 'snack' },
    { id: "S029", name: "Glass of Milk", image: "https://images.unsplash.com/photo-1596704122365-bf045a1c1a25", ingredients: [{ name: "Milk", baseQuantity: 1, unit: "cup" }], nutrition: { calories: 150, protein: 8, carbs: 12, fat: 8 }, recipe: "A simple glass of milk.", tags: ['vegetarian', 'gluten-free', 'nut-free', 'contains:dairy'], type: 'snack' },
    { id: "S030", name: "Pretzels", image: "https://images.unsplash.com/photo-1588439401339-7a0b303a7f80", ingredients: [{ name: "Pretzels", baseQuantity: 30, unit: "g" }], nutrition: { calories: 110, protein: 3, carbs: 23, fat: 1 }, recipe: "Salty and crunchy pretzels.", tags: ['vegan', 'vegetarian', 'dairy-free', 'nut-free', 'contains:gluten'], type: 'snack' },
];

export const PROTEINS: Meal[] = [
    { id: "P001", name: "Grilled Chicken", image: "https://images.unsplash.com/photo-1598515214211-89d3c7373094", ingredients: [ { name: "Chicken Breast", baseQuantity: 150, unit: "g", perPerson: true } ], nutrition: { calories: 220, protein: 40, carbs: 0, fat: 5 }, tags: ['gluten-free', 'dairy-free', 'nut-free'], type: 'lunch' },
    { id: "P002", name: "Baked Salmon", image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2", ingredients: [ { name: "Salmon Fillet", baseQuantity: 150, unit: "g", perPerson: true } ], nutrition: { calories: 280, protein: 35, carbs: 0, fat: 15 }, tags: ['gluten-free', 'dairy-free', 'nut-free'], type: 'lunch' },
    { id: "P003", name: "Pan-Seared Tofu", image: "https://images.unsplash.com/photo-1598579084127-1c39a1200235", ingredients: [ { name: "Firm Tofu", baseQuantity: 200, unit: "g", perPerson: true } ], nutrition: { calories: 180, protein: 20, carbs: 4, fat: 10 }, tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'lunch' },
    { id: "P004", name: "Sirloin Steak", image: "https://images.unsplash.com/photo-1551028150-64b9f398f67b", ingredients: [ { name: "Sirloin Steak", baseQuantity: 180, unit: "g", perPerson: true } ], nutrition: { calories: 300, protein: 45, carbs: 0, fat: 12 }, tags: ['gluten-free', 'dairy-free', 'nut-free'], type: 'lunch' },
    { id: "P005", name: "Sautéed Shrimp", image: "https://images.unsplash.com/photo-1599652136214-f06536109459", ingredients: [ { name: "Shrimp", baseQuantity: 150, unit: "g", perPerson: true } ], nutrition: { calories: 150, protein: 30, carbs: 1, fat: 2 }, tags: ['gluten-free', 'dairy-free', 'nut-free'], type: 'lunch' },
    { id: "P006", name: "Lentils", image: "https://images.unsplash.com/photo-1587329249718-3a434c764e51", ingredients: [ { name: "Cooked Lentils", baseQuantity: 1, unit: "cup", perPerson: true } ], nutrition: { calories: 150, protein: 12, carbs: 28, fat: 1 }, tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'lunch' },
    { id: "P007", name: "Ground Beef", image: "https://images.unsplash.com/photo-1603360431953-835318357c2b", ingredients: [ { name: "Ground Beef", baseQuantity: 150, unit: "g", perPerson: true } ], nutrition: { calories: 250, protein: 30, carbs: 0, fat: 14 }, tags: ['gluten-free', 'dairy-free', 'nut-free'], type: 'lunch' },
    { id: "P008", name: "Chickpeas", image: "https://images.unsplash.com/photo-1587329249718-3a434c764e51", ingredients: [ { name: "Canned Chickpeas", baseQuantity: 1, unit: "cup", perPerson: true } ], nutrition: { calories: 180, protein: 10, carbs: 35, fat: 3 }, tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'lunch' },
];

export const BASES: Meal[] = [
    { id: "BA01", name: "with Quinoa", image: "https://images.unsplash.com/photo-1579529458477-a3d5e21976a4", ingredients: [ { name: "Quinoa", baseQuantity: 0.5, unit: "cup", perPerson: true } ], nutrition: { calories: 160, protein: 6, carbs: 30, fat: 2 }, tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'lunch' },
    { id: "BA02", name: "over Rice", image: "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a7", ingredients: [ { name: "Rice", baseQuantity: 0.5, unit: "cup", perPerson: true } ], nutrition: { calories: 200, protein: 4, carbs: 45, fat: 0 }, tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'lunch' },
    { id: "BA03", name: "with Pasta", image: "https://images.unsplash.com/photo-1598866594240-a3b5a4562c83", ingredients: [ { name: "Pasta", baseQuantity: 100, unit: "g", perPerson: true } ], nutrition: { calories: 220, protein: 8, carbs: 45, fat: 1 }, tags: ['vegan', 'vegetarian', 'dairy-free', 'nut-free', 'contains:gluten'], type: 'lunch' },
    { id: "BA04", name: "and Roasted Potatoes", image: "https://images.unsplash.com/photo-1617470716844-3677a8711054", ingredients: [ { name: "Potatoes", baseQuantity: 150, unit: "g", perPerson: true } ], nutrition: { calories: 180, protein: 4, carbs: 40, fat: 1 }, tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'lunch' },
    { id: "BA05", name: "in a Salad Bowl", image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd", ingredients: [ { name: "Mixed Greens", baseQuantity: 2, unit: "cups", perPerson: true } ], nutrition: { calories: 50, protein: 2, carbs: 8, fat: 1 }, tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'lunch' },
    { id: "BA06", name: "with Couscous", image: "https://images.unsplash.com/photo-1628342419818-a6e4d2a13c24", ingredients: [ { name: "Couscous", baseQuantity: 0.5, unit: "cup", perPerson: true } ], nutrition: { calories: 180, protein: 6, carbs: 38, fat: 1 }, tags: ['vegan', 'vegetarian', 'dairy-free', 'nut-free', 'contains:gluten'], type: 'lunch' },
];

export const VEGGIES_AND_SAUCES: Meal[] = [
    { id: "V001", name: "and Steamed Broccoli", image: "https://images.unsplash.com/photo-1628773912693-0e446f8c926a", ingredients: [ { name: "Broccoli", baseQuantity: 1, unit: "cup", perPerson: true } ], nutrition: { calories: 50, protein: 4, carbs: 10, fat: 1 }, tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'lunch' },
    { id: "V002", name: "with Tomato Marinara", image: "https://images.unsplash.com/photo-1593362039989-15b630ee1b44", ingredients: [ { name: "Tomato Sauce", baseQuantity: 0.5, unit: "cup", perPerson: true } ], nutrition: { calories: 90, protein: 2, carbs: 15, fat: 2 }, tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'lunch' },
    { id: "V003", name: "in a Coconut Curry", image: "https://images.unsplash.com/photo-1569058242253-92a9c555a634", ingredients: [ { name: "Coconut Milk", baseQuantity: 0.25, unit: "cup", perPerson: true }, { name: "Curry Powder", baseQuantity: 1, unit: "tsp", perPerson: true } ], nutrition: { calories: 150, protein: 3, carbs: 8, fat: 12 }, tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'lunch' },
    { id: "V004", name: "with a Pesto Drizzle", image: "https://images.unsplash.com/photo-1606854293933-22b79a04a806", ingredients: [ { name: "Pesto", baseQuantity: 2, unit: "tbsp", perPerson: true } ], nutrition: { calories: 120, protein: 3, carbs: 2, fat: 12 }, tags: ['vegetarian', 'gluten-free', 'contains:dairy', 'contains:nuts'], type: 'lunch' },
    { id: "V005", name: "and Roasted Asparagus", image: "https://images.unsplash.com/photo-1554795808-3231c32711cf", ingredients: [ { name: "Asparagus", baseQuantity: 100, unit: "g", perPerson: true } ], nutrition: { calories: 40, protein: 4, carbs: 7, fat: 1 }, tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'lunch' },
    { id: "V006", name: "with Sautéed Mushrooms & Onions", image: "https://images.unsplash.com/photo-1595992359418-560a1d279b32", ingredients: [ { name: "Mushrooms", baseQuantity: 0.5, unit: "cup", perPerson: true }, { name: "Onion", baseQuantity: 0.25, unit: "cup", perPerson: true } ], nutrition: { calories: 70, protein: 3, carbs: 10, fat: 2 }, tags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], type: 'lunch' },
];

export const fetchAllPossibleMeals = async ({ preferences = [], allergies = [] }): Promise<Meal[]> => {
    const lowerCasePrefs = preferences.map(p => p.toLowerCase());
    const lowerCaseAllergies = allergies.map(a => a.toLowerCase().trim());
    
    const applyFilters = (items: Meal[]): Meal[] => {
        if (!Array.isArray(items)) {
            console.warn("applyFilters received a non-array value, returning empty.", items);
            return [];
        }
        return items.filter(item => {
            const hasAllergen = lowerCaseAllergies.some(allergy => item.tags.some(tag => tag === `contains:${allergy}`));
            const meetsPreferences = lowerCasePrefs.every(pref => item.tags.includes(pref) || item.tags.includes(`${pref}-optional`));
            return !hasAllergen && meetsPreferences;
        });
    };

    let allMeals: Meal[] = [];

    allMeals.push(...applyFilters(BREAKFAST_DB).map(m => ({ ...m, type: 'breakfast' })));
    allMeals.push(...applyFilters(SNACK_DB).map(m => ({ ...m, type: 'snack' })));

    const filteredProteins = applyFilters(PROTEINS);
    const filteredBases = applyFilters(BASES);
    const filteredVeggies = applyFilters(VEGGIES_AND_SAUCES);

    if (filteredProteins.length > 0 && filteredBases.length > 0 && filteredVeggies.length > 0) {
        for (const protein of filteredProteins) {
            for (const base of filteredBases) {
                for (const veggie of filteredVeggies) {
                    if (veggie.tags.includes('contains:dairy') && !protein.tags.includes('vegetarian')) continue;
                    if (veggie.tags.includes('contains:nuts') && lowerCaseAllergies.includes('nuts')) continue;

                    const combinedNutrition = { calories: Math.round((protein.nutrition.calories + base.nutrition.calories + veggie.nutrition.calories) / 5) * 5, protein: Math.round(protein.nutrition.protein + base.nutrition.protein + veggie.nutrition.protein), carbs: Math.round(protein.nutrition.carbs + base.nutrition.carbs + veggie.nutrition.carbs), fat: Math.round(protein.nutrition.fat + base.nutrition.fat + veggie.nutrition.fat) };
                    const combinedTags = [...new Set([...protein.tags, ...base.tags, ...veggie.tags])];
                    const combinedIngredients = [...protein.ingredients, ...base.ingredients, ...veggie.ingredients];
                    
                    const meal: Meal = {
                        id: `${protein.id}-${base.id}-${veggie.id}`,
                        name: `${protein.name} ${base.name} ${veggie.name}`,
                        image: protein.image,
                        type: 'lunch',
                        ingredients: combinedIngredients,
                        nutrition: combinedNutrition,
                        recipe: `Prepare {{${protein.ingredients[0].name}}} as desired. Cook {{${base.ingredients[0].name}}} according to package instructions. Prepare {{${veggie.ingredients[0].name}}} and combine everything to serve.`,
                        tags: combinedTags
                    };
                    allMeals.push(meal);
                }
            }
        }
    }
    
    return allMeals.filter((meal, index, self) => index === self.findIndex((m) => m.name === meal.name));
};